### ISSUE TITLE
Screen is not split over pursuit days

### ISSUE THREAD

**Issue by JereKuusela** [Myrten/CK3.Utils#3]
https://github.com/Myrten/CK3.Utils/blob/7226e61f7016ee58673caa77c738bb8f57053ade/CK3.Utils.BattleSimulator/Simulation/Army.cs#L94

Total screen should be divided by BattleSimulationConstants.PursuitDays

**Comment by Myrten** [comment]
Nice find, I had a feeling screen was too good
